name: Check stale issues and pull requests

on:
  schedule:
  # run daily at midnight UTC (12:00 am)
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-slim
    steps:
    - name: Check stale PR/issues
      uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
         # WHEN TO MARK STALE
        days-before-stale: 30
        # WHEN TO CLOSE AFTER STALE
        days-before-close: 7

        # STALE LABEL / COMMENT
        stale-issue-label: stale-issue
        stale-pr-label: stale-pr
        stale-issue-message: This issue has been automatically marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.
        stale-pr-message: This PR has been automatically marked as stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.
        
        # COMMENTS WHEN CLOSED
        close-issue-message: This issue was closed automatically after being stale for 7 days.
        close-pr-message: This pull request was closed automatically after being stale for 7 days.

        # CUSTOM FILTERS (optional)
        exempt-issue-labels: help wanted, documentation
        exempt-pr-labels: WIP
